server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:../frau_db
    username: sa
    password: sa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        trace: false